stages:
  - build

variables:
  MYSQL_DATABASE: ci_db
  MYSQL_USER: shopware
  MYSQL_PASSWORD: app
  MYSQL_SERVER: mysql
  MYSQL_ROOT_PASSWORD: root

build-sw6:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  services:
    - name: mysql:5.7
  script:
    - composer install -q
    - php vendor/bin/dep deploy:production production -vvv
