stages:
  - build

variables:
  MYSQL_DATABASE: ci_db
  MYSQL_USER: shopware
  MYSQL_PASSWORD: app
  MYSQL_ROOT_PASSWORD: root

build-sw5:
  stage: build
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  services:
    - name: mysql:5.7
      alias: mysql
  script:
    - composer install -q
    - php vendor/bin/dep deploy:test test -vvv
    - ls -la /tmp/deploy/current/ # ensure that everything worked fine
